### ISSUE TITLE
Error creating space: Unable to obtain keycloak client ID. Response status: 403 Forbidden

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8-platform#272]
After installing the in dev 4.x platform we get an error creating a space.  The space does actually get created but in the WIT pod logs is the 403:
```
{"action":"Show","bytes":117,"ctrl":"NamedspacesController","fields.time":"21.213088000000003ms","level":"info","msg":"completed","pkg":"log.LogRequest.func1","req_id":"m788qqXEUh-158","status":404,"time":"2017-06-15 14:50:38"}
{"GET":"/api/status","action":"Show","ctrl":"StatusController","from":"172.17.0.1","level":"info","msg":"request started","pkg":"log.LogRequest.func1","req_id":"m788qqXEUh-159","time":"2017-06-15 14:50:41"}
{"GET":"/api/status","action":"Show","ctrl":"StatusController","from":"172.17.0.1","level":"info","msg":"request started","pkg":"log.LogRequest.func1","req_id":"m788qqXEUh-160","time":"2017-06-15 14:50:41"}
{"action":"Show","bytes":124,"ctrl":"StatusController","fields.time":"0.951623ms","level":"info","msg":"completed","pkg":"log.LogRequest.func1","req_id":"m788qqXEUh-159","status":200,"time":"2017-06-15 14:50:41"}
{"action":"Show","bytes":124,"ctrl":"StatusController","fields.time":"1.6004990000000001ms","level":"info","msg":"completed","pkg":"log.LogRequest.func1","req_id":"m788qqXEUh-160","status":200,"time":"2017-06-15 14:50:41"}
{"OPTIONS":"/api/spaces","action":"preflight","ctrl":"SpaceController","from":"192.168.64.1","level":"info","msg":"request started","pkg":"log.LogRequest.func1","req_id":"m788qqXEUh-161","time":"2017-06-15 14:50:46"}
{"action":"preflight","bytes":0,"ctrl":"SpaceController","fields.time":"0.429186ms","level":"info","msg":"completed","pkg":"log.LogRequest.func1","req_id":"m788qqXEUh-161","status":200,"time":"2017-06-15 14:50:46"}
{"POST":"/api/spaces","action":"Create","ctrl":"SpaceController","from":"192.168.64.1","level":"info","msg":"request started","pkg":"log.LogRequest.func1","req_id":"m788qqXEUh-162","time":"2017-06-15 14:50:46"}
{"identity_id":"c3d2e308-9376-441f-af88-27b5c3d6c012","level":"info","msg":"Space created successfully","pkg":"space","req_id":"m788qqXEUh-162","space_id":"afb269ef-a2ed-4d33-bab4-935c64cecfc3","time":"2017-06-15 14:50:46"}
{"file":"/home/jenkins/go/src/github.com/fabric8io/almighty-core/auth/authz.go","func":"github.com/fabric8io/almighty-core/auth.GetClientID","level":"error","line":296,"msg":"Unable to obtain keycloak client ID","pid":1,"pkg":"auth","public_client_id":"fabric8-online-platform","req_id":"","response_body":"","response_status":"403 Forbidden","time":"2017-06-15 14:50:46"}
{"err":"Unable to obtain keycloak client ID. Response status: 403 Forbidden. Responce body: ","error_message":"Unable to obtain keycloak client ID. Response status: 403 Forbidden. Responce body: ","level":"info","msg":"an error occurred in our api","pkg":"jsonapi","time":"2017-06-15 14:50:46"}
{"action":"Create","bytes":175,"ctrl":"SpaceController","fields.time":"322.227506ms","level":"info","msg":"completed","pkg":"log.LogRequest.func1","req_id":"m788qqXEUh-162","status":500,"time":"2017-06-15 14:50:46"}
```

**Comment by rawlingsj** [comment]
In the keycloak logs we get more info:

```
15:23:51,832 ERROR [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-45) RESTEASY002005: Failed executing GET /admin/realms/fabric8/clients: org.keycloak.services.ForbiddenException
	at org.keycloak.services.resources.admin.RealmAuth.requireAny(RealmAuth.java:56)
	at org.keycloak.services.resources.admin.RealmAdminResource.<init>(RealmAdminResource.java:139)
	at org.keycloak.services.resources.admin.RealmsAdminResource.getRealmAdmin(RealmsAdminResource.java:205)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by hectorj2f** [comment]
This is related to the roles associated to the clients in the fabric8 realm for the `fabric8-online-platform` client. To assign them, you just need to go to the client and click on the tab Service Account Roles.
Next select the clients and assign them the following roles:
- `fabric8-online-platform` requires `uma_protection` role
- `broker` requires a `read-token` role
- `realm-management` requires `view-users` and `manager-authorization` roles

**Comment by hectorj2f** [comment]
Also, it is required to create two scopes in the client fabric8-online-platform -> Authorization - > Auth Scopes. These scopes are `read:space` and `admin:space`

**Comment by rawlingsj** [comment]
Ok awesome!   I'll have a crack at the automating that via the realm.json unless that's something you're already looking at? https://github.com/fabric8io/fabric8-platform/blob/master/apps/keycloak/src/main/fabric8/cm.yml#L14
