### ISSUE TITLE
Authentication using github or OpenShift v3 doesn't work

### ISSUE THREAD

**Issue by abouchama** [fabric8io/fabric8-platform#299]
When we try to authenticate in fabric8 console using github or OpenShift v3 it doesn't work.

```
$ oc get oauthclient
NAME                           SECRET                                 WWW-CHALLENGE   REDIRECT URIS
fabric8-online-platform        fabric8                                FALSE           https://keycloak-fabric8.192.168.42.16.nip.io/auth/realms/fabric8/broker/openshift-v3/endpoint
openshift-browser-client       599162f6-cd23-407a-be4d-b60234b538d5   FALSE           https://192.168.42.16:8443/oauth/token/display
openshift-challenging-client                                          TRUE            https://192.168.42.16:8443/oauth/token/implicit
openshift-web-console                                                 FALSE           https://192.168.42.16:8443/console/,https://localhost:9000
```

Here's the error received when i have tried to authenticate using OpenShift v3:

```
$ oc logs keycloak-6-23sfk

18:35:05,086 WARN  [org.keycloak.services] (default task-60) KC-SERVICES0091: Request is missing scope 'openid' so it's not treated as OIDC, but just pure OAuth2 request. This can have impact in future versions (eg. removed IDToken from the Token Response)
18:35:05,145 ERROR [org.keycloak.theme.ExtendingThemeManager] (default task-60) Failed to find LOGIN theme fabric8, using built-in themes
18:35:16,335 WARN  [org.keycloak.connections.httpclient.DefaultHttpClientFactory] (default task-3) Truststore is disabled
18:35:16,490 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-3) Failed to make identity provider oauth callback: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1899)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1420)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.keycloak.broker.provider.util.SimpleHttp.makeRequest(SimpleHttp.java:142)
	at org.keycloak.broker.provider.util.SimpleHttp.asString(SimpleHttp.java:90)
	at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:138)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:107)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:133)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:101)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.keycloak.services.filters.KeycloakSessionServletFilter.doFilter(KeycloakSessionServletFilter.java:90)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:46)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$36(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$40(UndertowDeploymentInfoService.java:1706)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$40(UndertowDeploymentInfoService.java:1706)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$40(UndertowDeploymentInfoService.java:1706)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$40(UndertowDeploymentInfoService.java:1706)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:90)
	at sun.security.validator.Validator.getInstance(Validator.java:179)
	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	... 77 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
	at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88)
	... 89 more
18:35:16,493 WARN  [org.keycloak.events] (default task-3) type=LOGIN_ERROR, realmId=fdda767b-96ea-4f4b-bb9b-4e7efb23465c, clientId=null, userId=null, ipAddress=192.168.42.1, error=identity_provider_login_failure
18:35:16,497 ERROR [org.keycloak.theme.ExtendingThemeManager] (default task-3) Failed to find LOGIN theme fabric8, using built-in themes
18:35:25,767 ERROR [org.keycloak.theme.ExtendingThemeManager] (default task-5) Failed to find LOGIN theme fabric8, using built-in themes
18:35:36,596 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (default task-12) Failed to make identity provider oauth callback: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1899)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1420)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.keycloak.broker.provider.util.SimpleHttp.makeRequest(SimpleHttp.java:142)
	at org.keycloak.broker.provider.util.SimpleHttp.asString(SimpleHttp.java:90)
	at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:138)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:107)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:133)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:101)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.keycloak.services.filters.KeycloakSessionServletFilter.doFilter(KeycloakSessionServletFilter.java:90)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:46)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$36(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$40(UndertowDeploymentInfoService.java:1706)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$40(UndertowDeploymentInfoService.java:1706)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$40(UndertowDeploymentInfoService.java:1706)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$40(UndertowDeploymentInfoService.java:1706)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:90)
	at sun.security.validator.Validator.getInstance(Validator.java:179)
	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	... 77 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
	at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88)
	... 89 more
18:35:36,597 WARN  [org.keycloak.events] (default task-12) type=LOGIN_ERROR, realmId=fdda767b-96ea-4f4b-bb9b-4e7efb23465c, clientId=null, userId=null, ipAddress=192.168.42.1, error=identity_provider_login_failure
18:35:36,598 ERROR [org.keycloak.theme.ExtendingThemeManager] (default task-12) Failed to find LOGIN theme fabric8, using built-in themes
```

**Comment by rawlingsj** [comment]
Interesting - I have seen this error before and it's why we have an [init container](https://github.com/fabric8io/fabric8-platform/blob/master/apps/keycloak/src/main/fabric8/keycloak-deployment.yml#L14-L28) which takes the default mounted [kubernetes secrets](https://github.com/fabric8io/fabric8-platform/blob/master/apps/keycloak/src/main/fabric8/keycloak-deployment.yml#L20-L21) and generates the [openshift-truststore.jks](https://github.com/fabric8io/fabric8-platform/blob/master/apps/keycloak/src/main/fabric8/keycloak-deployment.yml#L19)  and then mounts that file into the [keycloak container](https://github.com/fabric8io/fabric8-platform/blob/master/apps/keycloak/src/main/fabric8/keycloak-deployment.yml#L191)

Is this on minishift? 
What version?  
Also can you check the docker logs of the initcontainer to see if there's and extra info?

```
eval $(minishift docker-env)
docker ps -a | grep pemtokeystore
docker logs [container id]
```

**Comment by abouchama** [comment]
Thanks @rawlingsj ,

Yes, is minishift
```
$ minishift version
Minishift version: 1.0.0+4f8cb6d
CDK Version: 3.0.0
```
Unfortunately, there's no log :-(
```
$ eval $(minishift docker-env)
$ docker ps -a | grep pemtokeystore
ad9163659f3f        jimmidyson/pemtokeystore:v0.2.0                 "/pemtokeystore -k..."   About an hour ago   Exited (0) About an hour ago                       k8s_openshift-ca-pemtokeystore.6ad006c6_keycloak-6-23sfk_fabric8_a0d0719d-55de-11e7-94ca-525400600b2a_b8620878
$ docker logs ad9163659f3f
```
Below the logs of init container:
```
$oc logs init-tenant-2-9z4vw

{"GET":"/api/status","action":"Show","ctrl":"StatusController","from":"172.17.0.1","level":"info","msg":"started","req_id":"nB6I7AWm0C-830","time":"2017-06-20 18:59:58"}
{"action":"Show","bytes":124,"ctrl":"StatusController","fields.time":"642.06µs","level":"info","msg":"completed","req_id":"nB6I7AWm0C-830","status":200,"time":"2017-06-20 18:59:58"}
{"action":"Show","bytes":124,"ctrl":"StatusController","fields.time":"1.299714ms","level":"info","msg":"completed","req_id":"nB6I7AWm0C-829","status":200,"time":"2017-06-20 18:59:58"}
{"GET":"/api/status","action":"Show","ctrl":"StatusController","from":"172.17.0.1","level":"info","msg":"started","req_id":"nB6I7AWm0C-831","time":"2017-06-20 19:00:08"}
{"GET":"/api/status","action":"Show","ctrl":"StatusController","from":"172.17.0.1","level":"info","msg":"started","req_id":"nB6I7AWm0C-832","time":"2017-06-20 19:00:08"}
{"action":"Show","bytes":124,"ctrl":"StatusController","fields.time":"1.548659ms","level":"info","msg":"completed","req_id":"nB6I7AWm0C-831","status":200,"time":"2017-06-20 19:00:08"}
{"action":"Show","bytes":124,"ctrl":"StatusController","fields.time":"1.161148ms","level":"info","msg":"completed","req_id":"nB6I7AWm0C-832","status":200,"time":"2017-06-20 19:00:08"}
{"GET":"/api/status","action":"Show","ctrl":"StatusController","from":"172.17.0.1","level":"info","msg":"started","req_id":"nB6I7AWm0C-833","time":"2017-06-20 19:00:18"}
{"GET":"/api/status","action":"Show","ctrl":"StatusController","from":"172.17.0.1","level":"info","msg":"started","req_id":"nB6I7AWm0C-834","time":"2017-06-20 19:00:18"}
{"action":"Show","bytes":124,"ctrl":"StatusController","fields.time":"1.451106ms","level":"info","msg":"completed","req_id":"nB6I7AWm0C-834","status":200,"time":"2017-06-20 19:00:18"}
{"action":"Show","bytes":124,"ctrl":"StatusController","fields.time":"3.033364ms","level":"info","msg":"completed","req_id":"nB6I7AWm0C-833","status":200,"time":"2017-06-20 19:00:18"}
{"GET":"/api/status","action":"Show","ctrl":"StatusController","from":"172.17.0.1","level":"info","msg":"started","req_id":"nB6I7AWm0C-836","time":"2017-06-20 19:00:28"}
{"GET":"/api/status","action":"Show","ctrl":"StatusController","from":"172.17.0.1","level":"info","msg":"started","req_id":"nB6I7AWm0C-835","time":"2017-06-20 19:00:28"}
{"action":"Show","bytes":124,"ctrl":"StatusController","fields.time":"557.549µs","level":"info","msg":"completed","req_id":"nB6I7AWm0C-836","status":200,"time":"2017-06-20 19:00:28"}
{"action":"Show","bytes":124,"ctrl":"StatusController","fields.time":"2.131597ms","level":"info","msg":"completed","req_id":"nB6I7AWm0C-835","status":200,"time":"2017-06-20 19:00:28"}
{"GET":"/api/status","action":"Show","ctrl":"StatusController","from":"172.17.0.1","level":"info","msg":"started","req_id":"nB6I7AWm0C-837","time":"2017-06-20 19:00:38"}
{"GET":"/api/status","action":"Show","ctrl":"StatusController","from":"172.17.0.1","level":"info","msg":"started","req_id":"nB6I7AWm0C-838","time":"2017-06-20 19:00:38"}
{"action":"Show","bytes":124,"ctrl":"StatusController","fields.time":"1.156706ms","level":"info","msg":"completed","req_id":"nB6I7AWm0C-837","status":200,"time":"2017-06-20 19:00:38"}
{"action":"Show","bytes":124,"ctrl":"StatusController","fields.time":"1.69294ms","level":"info","msg":"completed","req_id":"nB6I7AWm0C-838","status":200,"time":"2017-06-20 19:00:38"}
{"GET":"/api/status","action":"Show","ctrl":"StatusController","from":"172.17.0.1","level":"info","msg":"started","req_id":"nB6I7AWm0C-839","time":"2017-06-20 19:00:48"}
{"GET":"/api/status","action":"Show","ctrl":"StatusController","from":"172.17.0.1","level":"info","msg":"started","req_id":"nB6I7AWm0C-840","time":"2017-06-20 19:00:48"}
{"action":"Show","bytes":124,"ctrl":"StatusController","fields.time":"846.048µs","level":"info","msg":"completed","req_id":"nB6I7AWm0C-840","status":200,"time":"2017-06-20 19:00:48"}
{"action":"Show","bytes":124,"ctrl":"StatusController","fields.time":"1.505701ms","level":"info","msg":"completed","req_id":"nB6I7AWm0C-839","status":200,"time":"2017-06-20 19:00:48"}
{"GET":"/api/status","action":"Show","ctrl":"StatusController","from":"172.17.0.1","level":"info","msg":"started","req_id":"nB6I7AWm0C-841","time":"2017-06-20 19:00:58"}
{"GET":"/api/status","action":"Show","ctrl":"StatusController","from":"172.17.0.1","level":"info","msg":"started","req_id":"nB6I7AWm0C-842","time":"2017-06-20 19:00:58"}
{"action":"Show","bytes":124,"ctrl":"StatusController","fields.time":"858.655µs","level":"info","msg":"completed","req_id":"nB6I7AWm0C-842","status":200,"time":"2017-06-20 19:00:58"}
{"action":"Show","bytes":124,"ctrl":"StatusController","fields.time":"5.247593ms","level":"info","msg":"completed","req_id":"nB6I7AWm0C-841","status":200,"time":"2017-06-20 19:00:58"}
```

**Comment by rawlingsj** [comment]
I know this isn't an ideal response but I wonder if you wouldn't mind upgrading to minishift v1.1.0?  It's a PITA I know but I'm not sure what could be causing it yet.

If you do then I tend to `minishift stop && minishift delete && rm -rf  ~/.minishift`

**Comment by abouchama** [comment]
np @rawlingsj, i will give it a try and i will keep you informed ;-) (It will take a while to download all images)

**Comment by abouchama** [comment]
Cool to get this feature of caching docker images and avoiding time to download all images. 
Good news, with the following versions it works like a charm, no more authentication problem:
```
$ minishift version
minishift v1.1.0
$ oc version
oc v1.5.1+7b451fc
```
Thanks lot @rawlingsj

**Comment by rawlingsj** [comment]
yay! no problem @abouchama we're working on a cpl more issues which should be fixed soon and reduce a ton of error notifications

**Comment by pszuster** [comment]
I'm having the same issue with these versions:
`minishift version
minishift v1.3.1+a2d3799
CDK v3.1.1-1

oc version
oc v3.6.173.0.21
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.10:8443
openshift v3.6.173.0.5
kubernetes v1.6.1+5115d708d7
`
Any idea what can it be?
