### ISSUE TITLE
Add a project to the space fails with "java.lang.IllegalArgumentException: E-mail address of PersonIdent must not be null."

### ISSUE THREAD

**Issue by abouchama** [fabric8io/fabric8-platform#306]
Hello,

When i add a project (starter or quickstart or existing code), it fails at Step6 : Build configuration with the following error message:

```
ExecuteForgeCommandError
The forge-starter :: execute :: 6 command failed or only partially succeeded

name = ForgeApiServerError
origin = Fabric8ForgeService
message = An unexpected server side forge api error occurred
inner = 
   httpError = 
      status = 500
      statusText = Internal Server Error
      url = https://forge-fabric8.192.168.42.106.nip.io/forge/commands/launchpad-new-starter-project/execute
      body = 
         results =  [             
             { 
               status = SUCCESS
             } ,            
             { 
               message = Created new Spring Boot project in directory: myspace
               status = SUCCESS
             } ,            
             { 
               status = SUCCESS
             } ,            
             { 
               message = Added Jenkinsfile to project
               status = SUCCESS
             } ,            
             { 
               message = Failed to import project to https://github.com/abouchama/myspace.git. java.lang.IllegalArgumentException: E-mail address of PersonIdent must not be null.
               status = FAILED
             } ,            
             { 
               message = Created OpenShift BuildConfig developer/myspace. Created Jenkins job: https://jenkins-developer-jenkins.192.168.42.106.nip.io/job/abouchama and added git webhooks to repositories myspace. 
               status = SUCCESS
             } ,            
             { 
               message = Already created BuildConfig developer/myspace
               status = SUCCESS
             }  ] 
```

**Comment by jstrachan** [comment]
I think I've fixed this one; just waiting on a new fabric8-platform release

**Comment by abouchama** [comment]
Thanks @jstrachan , i see a new release right now of fabric8-platform v4.0.1, is that one ?

**Comment by rawlingsj** [comment]
FWIW there's another (4.0.11) waiting to sync with maven central now

**Comment by abouchama** [comment]
Sorry, i was talking about that v4.0.11, i forgot (1) :-)
When it will be published on maven central, i will give it a test, thanks

**Comment by jstrachan** [comment]
yeah - I think that should have the fix!

**Comment by rawlingsj** [comment]
ok great - pipeline's finished so you should be able to test it now

**Comment by jstrachan** [comment]
ah sorry ignore me - the PRs haven't been automating yet
https://github.com/fabric8io/fabric8-platform/blob/master/pom.xml#L79

will do another soon

**Comment by abouchama** [comment]
@jstrachan : is time to test your PR on OpenShiftio as your demo ;-)

Executing `bash <(curl -s https://raw.githubusercontent.com/fabric8io/fabric8-platform/master/install.sh) ` is sufficient to update packages with the new release ?

**Comment by jstrachan** [comment]
;) just triggered a new fabric8-platform releases when this is done then yes the above should work

**Comment by jstrachan** [comment]
4.0.13 should be there now!

**Comment by abouchama** [comment]
Hi @jstrachan 

I just give it a try and i got the same error with another about creating organisation job,

```
ExecuteForgeCommandError
The forge-starter :: execute :: 6 command failed or only partially succeeded

name = ForgeApiServerError
origin = Fabric8ForgeService
message = An unexpected server side forge api error occurred
inner = 
   httpError = 
      status = 500
      statusText = Internal Server Error
      url = https://forge-fabric8.192.168.42.106.nip.io/forge/commands/launchpad-new-starter-project/execute
      body = 
         results =  [             
             { 
               status = SUCCESS
             } ,            
             { 
               message = Created new Spring Boot project in directory: order
               status = SUCCESS
             } ,            
             { 
               status = SUCCESS
             } ,            
             { 
               message = Added Jenkinsfile to project
               status = SUCCESS
             } ,            
             { 
               message = Failed to import project to https://github.com/abouchama/openshiftio-camelorder.git. java.lang.IllegalArgumentException: E-mail address of PersonIdent must not be null.
               status = FAILED
             } ,            
             { 
               message = Failed to create Jenkins Organisation job:: java.lang.IllegalStateException: Failed to create the GitHub Org Job at https://jenkins-developer-jenkins.192.168.42.106.nip.io/createItem?name=abouchama. javax.ws.rs.WebApplicationException: Failed to process https://jenkins-developer-jenkins.192.168.42.106.nip.io/createItem?name=abouchama and got status: 503 Service Unavailable
               status = FAILED
             } ,            
             { 
               message = Already created BuildConfig developer/order
               status = SUCCESS
             }  ] 
```

**Comment by rawlingsj** [comment]
The second one `Failed to create Jenkins Organisation job` is probably because the jenkins pod hasn't started in the developer-jenkins namespace.

**Comment by jstrachan** [comment]
yeah - I'm hoping to add a warning into the wizard if the users Jenkins isn't running when they try to create a project....

**Comment by abouchama** [comment]
Now, since jenkins pod started, we come back to the first error:

Below logs from forge pod:

```
2017-06-23 13:11:04,803 INFO  [io.fabric8.forge.generator.github.GithubRepoStep] (default task-34) Creating github repository user/vertx-payment
2017-06-23 13:11:08,744 INFO  [io.fabric8.forge.generator.github.GithubRepoStep] (default task-34) Created repository: https://github.com/abouchama/vertx-payment
2017-06-23 13:11:08,746 INFO  [io.fabric8.project.support.GitUtils] (default task-34) Trusting all SSL certificates
2017-06-23 13:11:08,750 INFO  [io.fabric8.forge.generator.github.GithubRepoStep] (default task-34) Initialised an empty git configuration repo at /tmp/projectDir6142965587256554056/vertx-payment
2017-06-23 13:11:08,750 ERROR [io.fabric8.forge.generator.github.GithubRepoStep] (default task-34) Failed to import project to https://github.com/abouchama/vertx-payment.git java.lang.IllegalArgumentException: E-mail address of PersonIdent must not be null.: java.lang.IllegalArgumentException: E-mail address of PersonIdent must not be null.
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:293)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:263)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:189)
	at io.fabric8.project.support.UserDetails.createPersonIdent(UserDetails.java:118)
	at io.fabric8.forge.generator.git.AbstractGitRepoStep.importNewGitProject(AbstractGitRepoStep.java:100)
	at io.fabric8.forge.generator.github.GithubRepoStep.execute(GithubRepoStep.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at io.fabric8.forge.generator.github.GithubRepoStep_$$_javassist_b2143c1f-b6b9-49d2-af78-e8c6140d27d9.execute(GithubRepoStep_$$_javassist_b2143c1f-b6b9-49d2-af78-e8c6140d27d9.java)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.execute(WizardCommandControllerImpl.java:161)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.execute(NoUIWizardControllerDecorator.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:124)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:97)
	at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_8fd3274a-2597-4d17-9757-9f1834ff3f0f.execute(CommandController_$$_javassist_8fd3274a-2597-4d17-9757-9f1834ff3f0f.java)
	at org.obsidiantoaster.generator.rest.ObsidianResource.executeCommandJson(ObsidianResource.java:483)
	at org.obsidiantoaster.generator.rest.ObsidianResource$Proxy$_$$_WeldClientProxy.executeCommandJson(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.swarm.generated.FaviconErrorHandler.handleRequest(FaviconErrorHandler.java:62)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

2017-06-23 13:11:08,894 INFO  [io.fabric8.project.support.BuildConfigHelper] (default task-34) Creating a BuildConfig for namespace: developer project: vertx-payment
2017-06-23 13:11:08,908 INFO  [io.fabric8.kubernetes.api.Controller] (default task-34) Using project: developer
2017-06-23 13:11:09,140 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-34) Got response code from Jenkins looking up credential: 200 message: OK from URL: https://jenkins-developer-jenkins.192.168.42.106.nip.io/credentials/store/system/domain/_/credentials/cd-github/ result: null
2017-06-23 13:11:09,409 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-34) Response from https://jenkins-developer-jenkins.192.168.42.106.nip.io/job/abouchama/config.xml is 200 OK
2017-06-23 13:11:09,512 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-34) Response from https://jenkins-developer-jenkins.192.168.42.106.nip.io/job/abouchama/config.xml is 200 OK
2017-06-23 13:11:09,514 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-34) Triggering the job https://jenkins-developer-jenkins.192.168.42.106.nip.io/job/abouchama
2017-06-23 13:11:09,562 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-34) Got response code from Jenkins: 302 message: Found from URL: https://jenkins-developer-jenkins.192.168.42.106.nip.io/job/abouchama/lastBuild/api/json
2017-06-23 13:11:09,562 ERROR [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-34) Failed to trigger job https://jenkins-developer-jenkins.192.168.42.106.nip.io/job/abouchama/lastBuild/api/json. Status: 302 message: Found
2017-06-23 13:11:09,562 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-34) Got last build JSON: null building: null
2017-06-23 13:11:09,562 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-34) Triggering Jenkins build: https://jenkins-developer-jenkins.192.168.42.106.nip.io/job/abouchama/build?delay=0
2017-06-23 13:11:09,677 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-34) Got response code from Jenkins: 302 message: Found from URL: https://jenkins-developer-jenkins.192.168.42.106.nip.io/job/abouchama/build?delay=0 Location: https://jenkins-developer-jenkins.192.168.42.106.nip.io/job/abouchama/
2017-06-23 13:11:10,988 INFO  [io.fabric8.forge.generator.github.GitHubFacade] (default task-34) Creating webhook at https://jenkins-developer-jenkins.192.168.42.106.nip.io/github-webhook/
2017-06-23 13:11:11,177 INFO  [io.fabric8.forge.generator.github.GitHubFacade] (default task-34) Got response code from github https://api.github.com/repos/abouchama/vertx-payment/hooks status: 201 message: Created
2017-06-23 13:11:11,237 WARN  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-34) Already created build developer/vertx-payment so returning
$ 
```

**Comment by jstrachan** [comment]
damn! its been working here after my patch.

Just out of interest how did you login to KeyCloak? I've been clicking the 'OpenShift' button, then it prompted me to type in my email address and stuff which is then saved in KeyCloak; then I synced the openshift developer account to my github user.  I wonder if different stuff happens if you login in a different way?

If you go to this page (assuming this is your ip address): https://keycloak-fabric8.192.168.64.82.nip.io/auth/realms/fabric8/account/ 
do you see the email, first name & last name populated?

I added code to try default the email from the github account if there's none in KeyCoak (which you should have an email address setup there too).

Lemme try add another fix though in case my previous fix wasn't enough!

**Comment by abouchama** [comment]
I click first on github button, then i have a page to type my email address and after i got the page to login with my OpenShift accounts (OpenShift login), at then end i received the page getting started in OpenShift.io with the following informations:

```
Connected accounts

Please connect your GitHub and OpenShift accounts to OpenShift.io.
Authorized accounts
You've authorized GitHub.
You've authorized OpenShift.com. 
```
In this page https://keycloak-fabric8.192.168.42.106.nip.io/auth/realms/fabric8/account, i got the same information that i have saved at the login page.

**Comment by petenorth** [comment]
I was getting this the 'E-mail address of PersonIdent must not be null.' error this morning when trying to add a quickstart (spring boot basic) to the space in a completely fresh openshift.io/fabric8 install.

I saw this issue thread and tried things again this afternoon.

It is now working for me and the space gets added to successfully.

The way I am initiating the logon to fabric8 (openshift.io) is to 

1) click on the logon link which appears at the top of the fabric8 home page
2) this takes you to a nicely formatted logon page with username and password fields and two buttons to the left one for github and one for openshift I chose github 
3) on all subsequent screens I just accepted to what ever it was asking access to.

Peter.

**Comment by aboucham** [comment]
Thanks @petenorth ,

Really bizarre, this is the same method that i use.

Even if i start from a completely fresh openshift.io/fabric8 install, I received the same error, i created a new github account but always the same.

```
oc logs -f forge-2-4w5xk

2017-06-28 08:58:58,234 INFO  [io.fabric8.forge.generator.github.GithubRepoStep] (default task-16) Creating github repository user/openshiftiodemo
2017-06-28 08:58:59,055 INFO  [io.fabric8.forge.generator.github.GithubRepoStep] (default task-16) Created repository: https://github.com/aboucham/openshiftiodemo
2017-06-28 08:58:59,061 INFO  [io.fabric8.project.support.GitUtils] (default task-16) Trusting all SSL certificates
2017-06-28 08:58:59,073 INFO  [io.fabric8.forge.generator.github.GithubRepoStep] (default task-16) Initialised an empty git configuration repo at /tmp/projectDir7157868706753221285/openshiftiodemo
2017-06-28 08:58:59,074 ERROR [io.fabric8.forge.generator.github.GithubRepoStep] (default task-16) Failed to import project to https://github.com/aboucham/openshiftiodemo.git java.lang.IllegalArgumentException: E-mail address of PersonIdent must not be null.: java.lang.IllegalArgumentException: E-mail address of PersonIdent must not be null.
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:293)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:263)
	at org.eclipse.jgit.lib.PersonIdent.<init>(PersonIdent.java:189)
	at io.fabric8.project.support.UserDetails.createPersonIdent(UserDetails.java:118)
	at io.fabric8.forge.generator.git.AbstractGitRepoStep.importNewGitProject(AbstractGitRepoStep.java:100)
	at io.fabric8.forge.generator.github.GithubRepoStep.execute(GithubRepoStep.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at io.fabric8.forge.generator.github.GithubRepoStep_$$_javassist_6d52ec90-a9ce-4231-bafd-b1fcb1f88f91.execute(GithubRepoStep_$$_javassist_6d52ec90-a9ce-4231-bafd-b1fcb1f88f91.java)
	at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.execute(WizardCommandControllerImpl.java:161)
	at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.execute(NoUIWizardControllerDecorator.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:124)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:97)
	at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_c16bf863-c787-4062-b768-d1306033e677.execute(CommandController_$$_javassist_c16bf863-c787-4062-b768-d1306033e677.java)
	at org.obsidiantoaster.generator.rest.ObsidianResource.executeCommandJson(ObsidianResource.java:483)
	at org.obsidiantoaster.generator.rest.ObsidianResource$Proxy$_$$_WeldClientProxy.executeCommandJson(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.swarm.generated.FaviconErrorHandler.handleRequest(FaviconErrorHandler.java:62)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

2017-06-28 08:58:59,152 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-16) Upserting Secret admin/cd-github
2017-06-28 08:58:59,513 INFO  [io.fabric8.project.support.BuildConfigHelper] (default task-16) Creating a BuildConfig for namespace: admin project: openshiftiodemo
2017-06-28 08:58:59,599 INFO  [io.fabric8.kubernetes.api.Controller] (default task-16) Using project: admin
2017-06-28 08:59:00,074 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-16) Got response code from Jenkins looking up credential: 200 message: OK from URL: https://jenkins-admin-jenkins.192.168.42.19.nip.io/credentials/store/system/domain/_/credentials/cd-github/ result: null
2017-06-28 08:59:00,166 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-16) Response from https://jenkins-admin-jenkins.192.168.42.19.nip.io/job/aboucham/config.xml is 200 OK
2017-06-28 08:59:00,381 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-16) Response from https://jenkins-admin-jenkins.192.168.42.19.nip.io/job/aboucham/config.xml is 200 OK
2017-06-28 08:59:00,382 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-16) Triggering the job https://jenkins-admin-jenkins.192.168.42.19.nip.io/job/aboucham
2017-06-28 08:59:00,434 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-16) Got response code from Jenkins: 302 message: Found from URL: https://jenkins-admin-jenkins.192.168.42.19.nip.io/job/aboucham/lastBuild/api/json
2017-06-28 08:59:00,434 ERROR [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-16) Failed to trigger job https://jenkins-admin-jenkins.192.168.42.19.nip.io/job/aboucham/lastBuild/api/json. Status: 302 message: Found
2017-06-28 08:59:00,434 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-16) Got last build JSON: null building: null
2017-06-28 08:59:00,434 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-16) Triggering Jenkins build: https://jenkins-admin-jenkins.192.168.42.19.nip.io/job/aboucham/build?delay=0
2017-06-28 08:59:00,565 INFO  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-16) Got response code from Jenkins: 302 message: Found from URL: https://jenkins-admin-jenkins.192.168.42.19.nip.io/job/aboucham/build?delay=0 Location: https://jenkins-admin-jenkins.192.168.42.19.nip.io/job/aboucham/
2017-06-28 08:59:01,310 INFO  [io.fabric8.forge.generator.github.GitHubFacade] (default task-16) Creating webhook at https://jenkins-admin-jenkins.192.168.42.19.nip.io/github-webhook/
2017-06-28 08:59:01,632 INFO  [io.fabric8.forge.generator.github.GitHubFacade] (default task-16) Got response code from github https://api.github.com/repos/aboucham/openshiftiodemo/hooks status: 201 message: Created
2017-06-28 08:59:01,709 WARN  [io.fabric8.forge.generator.kubernetes.CreateBuildConfigStep] (default task-16) Already created build admin/openshiftiodemo so returning
```

**Comment by aboucham** [comment]
I just tested again this morning with the latest version , and the problem disappear after the configuration of my profile in git, by setting the complete name & the principal email address.

We can close this issue.
Thanks @jstrachan & @rawlingsj

**Comment by jstrachan** [comment]
@aboucham awesome thanks!
